- matrix/Matrix.hpp
- matrix/Vector.hpp
More generalisable, fixes the sign comparison bug
> use size_t instead of int for for loops

- CMakeLists.txt
- matrix/Dcm.hpp
- matrix/Euler.hpp
- matrix/Matrix.hpp
- matrix/Quaternion.hpp
- matrix/Scalar.hpp
- matrix/SquareMatrix.hpp
- matrix/Vector.hpp
- matrix/Vector2.hpp
- matrix/Vector3.hpp
- matrix/filter.hpp
- matrix/integration.hpp
- test/attitude.cpp
See the commit messages
Since this library is intended to be used with px4 I tried to avoid a hard dependency on stdlib. Enabling support for  the << operator (`std::cout << Matrix`) is optional. Let me know if you prefer to handle this differently.
> scalar multiplication; std::cout support

- matrix/Matrix.hpp
This PR is to correct what appears to be a few index copy/paste errors that would function properly on square matrices but likely not in other cases.
> Matrix index correction to allow non-square matrices to evaluate properly.

- matrix/Matrix.hpp
- test/matrixAssignment.cpp
The Column Vector you are copying from, only has one Column and it is indexed by 0 not 1.
I also completed the unit test stub that would have found this bug.
> Matrix.setCol off by one bug fixed

- matrix/Euler.hpp
* Remove all body and inertial frame expressions
* Unify the description of the 3-2-1 intrinsic Tait-Bryan rotation sequence
* Unify the description of constructors and according set_from_xx functions
@tumbili can you check the changes? What is the status of the separate set_from_xx functions, do we need them or do we revert? (refering to https://github.com/PX4/Matrix/pull/19#issuecomment-218123937)
> Documentation improvements

- matrix/Euler.hpp
- matrix/Quaternion.hpp
GCC output:
error: implicit conversion from ‘float’ to ‘double’ to match other operand
of binary expression [-Werror=double-promotion]
> Euler, Quaternion: fix compiler errors for GCC 6.1.1

- matrix/Dcm.hpp
- matrix/Quaternion.hpp
- test/attitude.cpp
@MaEtUgR Thanks for spotting this. I'm not familiar with the pivot method in relation to dcm to quaternion conversion. I've corrected this to what I intended below. Let me know if this looks good to you.
> Fix for zero check on quat from dcm ctor.

- matrix/AxisAngle.hpp
- matrix/Matrix.hpp
- matrix/Quaternion.hpp
- matrix/SquareMatrix.hpp
- matrix/Vector.hpp
- matrix/helper_functions.hpp
- matrix/math.hpp
- matrix/stdlib_imports.hpp
- test/attitude.cpp
- test/filter.cpp
- test/hatvee.cpp
- test/helper.cpp
- test/integration.cpp
- test/inverse.cpp
- test/matrixAssignment.cpp
- test/matrixMult.cpp
- test/matrixScalarMult.cpp
- test/setIdentity.cpp
- test/slice.cpp
- test/squareMatrix.cpp
- test/test_macros.hpp
- test/transpose.cpp
- test/vector.cpp
- test/vector2.cpp
- test/vector3.cpp
- test/vectorAssignment.cpp
Please refer there for context: https://github.com/PX4/Firmware/pull/6829#issuecomment-286920967.
The root of the problem is an improper use of the math library. The templated classes were implicitly making assumptions about the scalar type. For example, in many places the library used to make references to `::sinf` or `::sqrt`, essentially assuming that the scalar type is float or double, respectively.
Normally, this problem would be really easy to fix; consider the following two of the most obvious approaches:
* Replace all references to the C standard library with alternative references to the C++ standard library by adding `std::` where necessary. This approach is pretty straightorward, but lacks in two ways:
* A lot of code modifications.
* No proof against re-occurrence of the same …
> Fixing misuse of the standard math library (performance audit)

- matrix/AxisAngle.hpp
- matrix/Dcm.hpp
- matrix/Euler.hpp
- matrix/Matrix.hpp
- matrix/Quaternion.hpp
- matrix/Scalar.hpp
- matrix/Vector.hpp
- matrix/Vector2.hpp
- matrix/Vector3.hpp
The matrix  base class and types implemented virtual dtors. This is a useful idea if any of the derivative types stored their own data, but none actually do. Instead we have a bunch of helper types that define useful domain specific methods to interact with the underlying Matrix data type.
This saves about 9k in flash on STM32F4 NuttX builds, and has a negligible impact on performance.
> Remove unnecessary virtualization overhead

- matrix/Quaternion.hpp
- test/attitude.cpp
It is about time we got this switched over. Can we get the necessary changes in to EKF2 @priseborough . Closes #29.
The changes to the unit test should show you all that will need to be changed in EKF2.
> Changes for hamilton quaternion convention.

- matrix/Matrix.hpp
- matrix/Quaternion.hpp
- test/attitude.cpp
- Matrix `print()` buffer was usually to small and characters went missing. No memory corruption occured with a too small buffer because of the snprintf checks.
- I tried to improve the comments for Quaternion derivative and conjugate to allow people to quickly understand and hopefully also take advantage of the quaternion based functionality instead of always taking the detour to dcms.
- In my opinion I found a bug in the `rotate()` method sice we switched to the Hamilton convention (https://github.com/PX4/Matrix/pull/34). In the useful convention we commited to the quaternion multiplication order to rotate frames corresponds to the order that equivalent rotation matrices have and hence we need to multiply from the left to rotate a frame by a certain amount. (see section 2.6 on page 26 …
> Matrix Print Buffer and Quaternion Fixes

- matrix/Vector.hpp
- test/vector.cpp
Original idea:
I came across normalization with zero check again and again and again in the code. Why not make it part of the library? It's not default, you still get `[NaN,NaN,NaN]` when executing `[0,0,0].unit();` but in case you already know you want a zero vector to stay zero, let's offer it.
While writing the tests for the new method I had a closer look at the vector.cpp tests and found:
- `make check` didn't run locally on GCC 5.4.0 for me because of loop unrolling signed overflow warning together with -Werror resulted in compile errors. It seems that CI does less optimization for the tests...
- `normalize()` is **another stub test** which only gets called but not evaluated
- no structure and comments
- the `operator*` dot product check reinitialized all data unnecessarily
So I …
> Normalization with Zero Check, fixed stub test again

- .gitignore
- matrix/Matrix.hpp
- matrix/Quaternion.hpp
- test/CMakeLists.txt
- test/attitude.cpp
- test/copyto.cpp
Based on the suggestion/discussion here: https://github.com/PX4/Matrix/pull/56#issuecomment-344663324 I add a copyTo method for generally any Matrix including vectors and quaternions for which is supposedly used the most.
- Because copying memory only allows for row-major order I wrote a method to also support **column-major** order.
- I include all the unit tests of course which deserve their **own test script** for clarity.
> CopyTo functionality for any Matrix

- matrix/Matrix.hpp
- test/copyto.cpp
because most uORB messages still contain all components of a vector one by one after each other
I discussed with @bkueng that the messages should stay like they are short-term for compatibility with flight review.
> Matrix: added copyToRaw method to allow copying to a pointer

- matrix/Quaternion.hpp
- matrix/Vector.hpp
- test/attitude.cpp
- test/vector.cpp
There are multiple application scenarios but I need this functionality for the quaternion controller: https://github.com/PX4/Firmware/pull/8003
And because of the reusability and the calculation itself suffering tedious corner cases I added it to the library with unit tests to ensure proper results.
A simple explanation for the corner cases: The input vectors are parallel but oposite and therefore require a 180 degree rotation but the cross product to get the perpendicular rotation axis is zero. For more discussion see: https://stackoverflow.com/questions/1171849/finding-quaternion-representing-the-rotation-from-one-vector-to-another .
> Quaternion: Shortest rotation between two vectors

- LICENSE
These minor changes allow github to recognize the license and display the tag.
I believe only the first line change is actually needed.
> LICENSE minor changes to template

- matrix/helper_functions.hpp
Using PX4_ISFINITE outside of PX4 is kind of questionable, but at a minimum should include the header rather than depend on magically inclusion ordering.
> helper_functions include required px4_defines header

- matrix/Quaternion.hpp
This is necessary if you want to call these methods on const Quaternions (depending on compiler warnings).
> Quaternion mark const helpers const

- matrix/AxisAngle.hpp
- matrix/Dcm.hpp
- matrix/Euler.hpp
- matrix/Matrix.hpp
- matrix/Quaternion.hpp
- matrix/Scalar.hpp
- matrix/SquareMatrix.hpp
- matrix/Vector.hpp
- matrix/Vector2.hpp
- matrix/Vector3.hpp
- test/matrixAssignment.cpp
Saves ~ 7.7KB of flash in px4fmu-v3_default.
> use default constructors and skip unnecessary initialization

- README.md
- matrix/Vector2.hpp
- test/vector2.cpp
The PX4 Firmware (in Flight Tasks) contains code like:
```
Vector2f vel(&_velocity(0));
Vector2f vel_sp_xy = Vector2f(&_velocity_setpoint(0));
```
This is unnecessary hard to read. We can simplify the code by adding an explicit constructor for Vector2 from Vector3, so that we can write:
```
Vector2f vel(_velocity);
Vector2f vel_sp_xy(_velocity_setpoint);
```
@Stifael @MaEtUgR
> Vector2 from Vector3 constructor

- matrix/Matrix.hpp
- test/copyto.cpp
Reaction to https://github.com/PX4/Firmware/pull/10117/
It used a pointer and could therefore not do correct type checking
for index out of bound or struct memebr order.
Has to be considered unsafe and bad practise.
We should switch to arrays as representation for vectors
inside the messages instead of foo_x, foo_y, foo_z fields.
> Matrix: remove unsafe copyToRaw method

- matrix/Quaternion.hpp
Functional change: do not recalculate the dot product in the normal case
Comments: a bit more clear and synced up with the prototyping script: https://github.com/Auterion/Flight_Control_Prototyping_Scripts/pull/1
> Small quaternion from vector improvements

- matrix/stdlib_imports.hpp
`<cinttypes>` isn't available in the NuttX c++ library.
> stdlib_imports cinttypes currently unavailable in NuttX toolchain

- matrix/Matrix.hpp
- test/slice.cpp
I had a look at the implementation of `slice`, and I found it odd that it doesn't have a copy loop. The current implementation does a raw memcpy of the underlying contiguous row-major data. As far as I can tell, this could only slice along rows. Interestingly, I found that the tests only tested for slicing along rows, so this bug would go unnoticed.
I added some tests that checks slicing along columns also. I have a feeling this would break, and we need to fix the implementation of `slice`. However I could be wrong, and hence I'm submitting these tests first to verify.
> Add slicing tests that are not pure row slicing

- matrix/Quaternion.hpp
- test/attitude.cpp
Added function that will get you the quaternion in canoncial form. A canonical quaternion has an non-negative real part. If it has a negative real part, multiplying every component with -1 will bring it to canonical form. Both quaternion will represent the same orientation.
> Canonical Quaternion

- matrix/Euler.hpp
- matrix/Matrix.hpp
- matrix/helper_functions.hpp
- matrix/stdlib_imports.hpp
- test/helper.cpp
~Using a loop to recreate a division is not a good solution and the additional limit for the cycle count doesn't make it better. Instead there exists efficient functionality in cmath to calculate
the remainder of a floating point devision: fmod.~
~Probably we can make it even more efficient by inlining which I suppose the compiler already does automatically. And adding a check if the value is already in range but I'm not sure if that really safes any compute.~
**EDIT:** I learned my lesson about `fmod` being among the least efficient math library methods I've seen both in compute and memory.
Instead this pr brings:
- generalized wrapping for any range
- more wrapping tests
- a fix for the `isEqual` method that's only used in testing but was duplicating the `print()` method while still …
> Improve wrapping helper functions including tests

- matrix/helper_functions.hpp
- test/helper.cpp
There was a bug in the wrapping function which returned NAN for wrapping a value equal to the lower boundary. E.g wrap(0.0, 0.0, 360.0) = nan
> fix bug in matrix wrap function

- matrix/helper_functions.hpp
- test/helper.cpp
After trying to bring the last wrap into the firmware, we discovered it was too big. It seems to have a disproportionate size due to inlining. This is a smaller version, that should still be fast.
Input arguments for low/high are in all cases I saw, const, so I explicitly inverted and multiplied the range in the floor so we don't have a divide due to compiler const propagation, see https://godbolt.org/z/RYZIoR
It also has a 'happy path' with no extra work, for the 99% case where things don't require wrapping.
This drops the codesize in FMUv2 by more than 700 bytes in my testing.
> Smaller code size wrap

- matrix/Vector.hpp
- test/vector.cpp
Currently the only usage of `pow` on vector is with a constant argument of 0.5, for sqrt. This is inefficient and increases codesize.
This PR replaces the calls to pow with argument 0.5, with sqrt. Firmware PR [coming soon](https://github.com/PX4/Firmware/tree/pr-remove-calls-to-pow)
Proof GCC does not transform pow(x,0.5) into a sqrt instruction: https://godbolt.org/z/Cu7dQh
> Replace pow with sqrt

- matrix/Vector.hpp
Previous PR the compiler was mixed up with float overloads, which are tricky in matrix due to macros which try to replace C libs with hacky C++ wrappers. This adds some extras which help the resolution, so we don't get float->double->float conversions accidentally.
> Help compiler with name resolution to avoid overload mixups

- matrix/Dcm.hpp
- matrix/Matrix.hpp
- matrix/Slice.hpp
- matrix/SquareMatrix.hpp
- matrix/Vector.hpp
- matrix/Vector2.hpp
- matrix/Vector3.hpp
- matrix/math.hpp
- test/slice.cpp
- test/squareMatrix.cpp
- test/vector3.cpp
This PR is inspired by the Eigen API, which has a writable `.block()` function.
In order to achieve this, I've made a Slice which acts as a temporary, to decide how data assigned to/from the `.slice()` function is treated.
Testing in the PX4 firmware, it compiles binaries to exactly the same size as before despite the use of the additional temporary struct.
> Write to slices

- matrix/Matrix.hpp
- test/attitude.cpp
- test/matrixAssignment.cpp
- test/matrixMult.cpp
- test/upperRightTriangle.cpp
This PR removes the `.data()` function which allowed unsafe access to the internal data structures of Matrix.
@dagar
> Remove direct access to internal data

- matrix/Matrix.hpp
- test/copyto.cpp
Before, if the array of fixed size was passed as a function argument, it would instead be treated as a pointer since we are taking a reference of it. This fixes that, allowing an array to be passed into a function and then a Matrix.copyTo() to work.
> Don't lose array sizes in copyTo

- matrix/AxisAngle.hpp
- matrix/LeastSquaresSolver.hpp
- matrix/Matrix.hpp
- matrix/Quaternion.hpp
- matrix/SquareMatrix.hpp
- matrix/helper_functions.hpp
- matrix/math.hpp
- test/helper.cpp
- test/matrixAssignment.cpp
- test/matrixMult.cpp
While writing unit tests for position control in https://github.com/PX4/Firmware/pull/12072 I had tests passing when I intentionally broke them. I tracked it down to the matrix library reporting `a == b` being `true` even though the elements were different if on either side there was a `NAN` in that specific position.
This pr fixes the problem, adds tests for it and resolves all the issues that were covered by tests that passed even though they should have failed.
> Fix equality checks, NAN being equal to any number

- matrix/AxisAngle.hpp
- matrix/Dcm.hpp
- matrix/Matrix.hpp
- matrix/Quaternion.hpp
- matrix/SquareMatrix.hpp
- matrix/Vector.hpp
- matrix/Vector2.hpp
- matrix/Vector3.hpp
- test/attitude.cpp
to avoid accidental implicit casts like e.g.
`Vector3f v = 0;`
assigning nullpointer content.
I have the Firmware pr ready to account for this restriction.
I still don't understand why the compiler implicitly allows above the above assignment which leads to an immediate segfault. It even allows it if the Vector constructors are not explicit but only the Matrix one they call. So you can wrap and explicit constructor in a non-explicit inheriting one...
Something remaining I still don't understand is the array size not getting checked:
```
float a[6] = {};
Vector3f v(a);
```
compiles just fine. I assume the intent of @dagar were compile time checks for array sizes in https://github.com/PX4/Matrix/pull/72
> Make all array constructors explicit

- matrix/Matrix.hpp
- matrix/Slice.hpp
- matrix/Vector.hpp
- test/copyto.cpp
- test/matrixAssignment.cpp
- test/slice.cpp
- test/vector.cpp
This adds a few utility functions to make some common operations easier.
* ` vector.longerThan(float)` and `slice.longerThan(float)`. This is useful for checks, to hide the more efficient comparison of squared values while not making the code ugly. eg. `if (vel.xy().longerThan(VEL_HOR_LIMIT)) { ... } `
* `norm()` and `norm_squared()` added to Slice. For things like `vector3.xy().norm()` or `matrix3f.row(0).norm()`
* `copyTo(float[])` for a Slice. Don't need a matrix temporary to do `matrix3f.row(3).copyTo(buf)`
* Take a slice of a slice. Some things are easier to think about as sub-blocks, rather than absolute coordinates. Eg `Vector3f z_accel_variances = matrix<float,25,25>.slice<3,3>(6,6).slice<3,1>(1,0)`. This is mostly to make it easier to understand.
> More features: longerThan, norm, copyTo and slice on a Slice

- matrix/Dual.hpp
- test/dual.cpp
Solution for https://github.com/PX4/Firmware/pull/13336
Unfortunately this is non-standard naming, so it isn't quite as find-replace as the old way. Hopefully gcc upgrades will let us go back to the old way.
> Fix weird C preprocessor conflicts

- matrix/Matrix.hpp
In addition to updating the toolchain, this fixes the GCC 4.8 bug directly.
For reference:
https://github.com/PX4/Firmware/pull/13336
https://github.com/PX4/rpi_toolchain/pull/1
> Work around GCC-4.8 bug

- test/attitude.cpp
This PR adds a test for the setIdentity function in the case of a quaternion. The identity quaternion is with the Matrix convention is [1,0,0,0]. The base class matrix::setIdentity() provides the necessary functionality, but this is not obvious and was not tested yet.
@jkflying
> test setIdentity function for quaternion

- .gitignore
- matrix/Dcm.hpp
- matrix/PseudoInverse.hpp
- matrix/PseudoInverse.hxx
- matrix/math.hpp
- test/CMakeLists.txt
- test/pseudoInverse.cpp
The implementation is based on this publication:
Courrieu, P. (2008). Fast Computation of Moore-Penrose Inverse Matrices, 8(2), 25–29. http://arxiv.org/abs/0804.4809
It is a fully templated implementation to guaranty type correctness.
> Add implementation of pseudo-inverse

- matrix/Vector.hpp
I was trying to use these functions from a scope that only had a const Vector available that's how I fond this "problem". I think it makes sense to keep read only declared as const.
> Vector: switch read only functions to const

- matrix/Slice.hpp
- test/slice.cpp
Adding read access to the diagonal elements of a slice. For non-square slice, the returned vector containing the diagonal elements will have the length of the smaller dimension of the slice.
This is helpful for extracting contiguous diagonal elements of a bigger matrix.
> Getting the slice diagonals

- matrix/AxisAngle.hpp
The existing implementation of AxisAngle(Quaternion) caused the strange behavior in SITL flights in https://github.com/PX4/ecl/pull/696. The new implementation is known to be numerically more robust and is solving this issue.
Two other constructors were missing the call to AxisAngle(Quaternion)
Good reference for formulas: https://github.com/ANYbotics/kindr/blob/master/doc/cheatsheet/cheatsheet_latest.pdf
> Fix AngleAxis constructors

- matrix/SquareMatrix.hpp
- test/inverse.cpp
This adds a template specification for the computation of the matrix inverse for the 2x2 and 3x3 case. The template specification is done in terms of the analytic expression. This could help to make the computation of the inverse in these case more efficient. In the worst case it for sure not less efficient and is also not adding to the size of an executable.
> Analytic inverse implementation

- matrix/AxisAngle.hpp
Follow up @dagar's suggestion: https://github.com/PX4/Matrix/pull/117#discussion_r361816250
This is important depending on the platform because norm() calls matrix::squrt() which dispatches correctly to the implementation for the used type. Otherwise float squrt()s can get calculated as double.
> AxisAngle: call q.imag().norm() for conversion

- matrix/Matrix.hpp
- test/matrixAssignment.cpp
**Problem**
In https://github.com/PX4/Matrix/commit/33a629105c266c8ed75ea5c78dcea850374d124c I added unit tests for the print function of matrices because previously it was just called but not really tested. Since then I found cases in which the predicted buffer size to save the characters to print was exceeded which is still memory safe since I started using snprintf in https://github.com/PX4/Matrix/commit/65679fbcbb4b31a1a77f3dc5268ca78ca95b3bf3#diff-b6575389f05f11bcd22c23d3e24bc7a6R281 but cuts the end of the output which results in not printing the last numbers or digits you want to see.
**Cause**
Apparently printf of %8.8g can result in 8 significant digits + dot + scientific notation e.g. "e+12" = 14 bytes I didn't calculate the scientific notation digits because I presumed they are …
> Matrix: correct print buffer size prediction

- matrix/Matrix.hpp
- test/matrixAssignment.cpp
Reason for this is the incompatibility of using fnprintf() found here: https://github.com/PX4/Firmware/pull/14374
I want to switch the print() function back to use printf() such that it's fully compatible with all (embedded) platforms. The tests should be nonintrusive.
To still test the print function I'm capturing stdout into a file such that the print() function can stay unchanged and the result of the printf()s can be evaluated.
> Matrix: capture stdout for print() test

- matrix/Quaternion.hpp
Most often the multiplication in convention descriptions and papers is described in matrix multiplication style like this:
I'm just **rearanging the terms which is a pure refactor** such that it's easily comparable with these definitions additional to it being clearly described by documenting we use the hamilton convention.
> Quaternion: refactor multiplication to matrix multiplication style

- matrix/Slice.hpp
- test/slice.cpp
In multiple occasions, I was missing the functionality of extracting a part of an matrix, scaling the part and assigning it to another variable.
Return type for the operator is chosen to be of Matrix<Type, P, Q>, since Slice does not hold data itself.
> Add operator* and operator/ for slice

- matrix/Quaternion.hpp
> Quaternion: Use template type instead of single hardcoded type

- matrix/Matrix.hpp
- matrix/Slice.hpp
- matrix/Vector.hpp
Proposed by @jkflying while he helped me debugging an independent issue.
I'm not entirely sure about the difference in practice. My code ran fine with and without this change.
> Switch operator() to return a const reference

- matrix/Matrix.hpp
- matrix/Slice.hpp
- matrix/SquareMatrix.hpp
- matrix/Vector.hpp
GCC 10 gives a warning "comparison of unsigned expression in ‘>= 0’ is always true" for these asserts since checking if an unsigned integer cannot be negative and hence the statement gets dropped.
I'd prefer to fix these instead of just disabling the warning since the warning is right and could unveil some real issues in other cases.
```
$ gcc --version
gcc (GCC) 10.1.0
```
<details><summary>Click for full compile output</summary>
```
$ make check
Scanning dependencies of target vector3
[  2%] Building CXX object test/CMakeFiles/vector3.dir/vector3.cpp.o
In file included from /home/maetugr/Firmware/src/lib/matrix/matrix/math.hpp:3,
from /home/maetugr/Firmware/src/lib/matrix/test/vector3.cpp:3:
/home/maetugr/Firmware/src/lib/matrix/matrix/Vector.hpp: In instantiation of ‘Type& …
```
> Remove asserts for unsigned integer >= 0

- matrix/Quaternion.hpp
- test/attitude.cpp
While looking into implementing a new heading calculation for https://github.com/PX4/Firmware/pull/13535 I found some points in the quaternion implementation that I stumble over and over again. So it's time to fix them.
- The conversion functions marked with `XXX DEPRECATED` are there since I first saw the matrix library and are duplicate to the conversion constructors.
- I adjusted the existing conversion tests to use the constructors instead. While doing so I found some confusing reuse of `qI` which was set to the identity quaternion but then changed later on so I refactored the tests.
- The half angle computed for the axis angle conversion was computed using a float once instead of the template type.
> Quaternion maintenance: remove deprecated functions

- matrix/Vector.hpp
- matrix/Vector2.hpp
- matrix/Vector3.hpp
- test/slice.cpp
Previously vectors could only be constructed from slice<M,1>.
> Construct Vector from Slice<1,M> alias row()

- matrix/SparseVector.hpp
- test/sparseVector.cpp
We need a way to iterate over the data stored in the SparseVector. Since in a loop the index is not known at compile time, the current at<>() function can not be used. Add a runtime access version like at(i) that looks up the compressed index, is an expansive operation. Therefore I suggest we force the client to access the data directly via the compressed index. The actual index can be recovered with the index() function.
> add possibility to iterate over SparseVector data at runtime

- matrix/helper_functions.hpp
- test/helper.cpp
I think wrap() in the helper functions fails in some corner cases when used with integer types.
Should it work with integer types? It's templated in such a way that you can certainly invoke it with ints, but it may not be intended for that. In any case, I have a fix, but I'm pushing some failing integer wrap tests first to see the CI fail.
If wrap() isn't meant to work with integer types, then should probably at least document it in the functions docstring,
or preferably use some clever template magic to make it not compile when Type is deduced to an integer type.
See the commit messages for more detail!
> Make wrap() work with integer types

- matrix/Matrix.hpp
This fixes the warning appearing with GCC 10.2:
```
../../src/lib/matrix/matrix/Matrix.hpp:481:34: error: logical ‘and’ of equal expressions [-Werror=logical-op]
481 |         for (size_t i = 0; i < M && i < N; i++) {
|
```
I would prefered something with `if constexpr` but we don't have that yet
in because we're using C++14.
> Matrix: fix warning if M == N

- matrix/helper_functions.hpp
Without inline we get multiple definitions during linking.
> matrix: inline to prevent multiple definitions

- matrix/helper_functions.hpp
> Fix clang-tidy warnings

- matrix/PseudoInverse.hxx
There were some cases that the results of pseudo inv becomes a null matrix when the input matrix is a floating-point number matrix such as follow: 
As a result, the actuators output unexpected values as follow:
I found out that the problem occurs as the precision of the tolerance for the float variables is too big, which is bigger than typical floating number precision(typically 7, reference: https://www.learncpp.com/cpp-tutorial/floating-point-numbers/).
So I simply decreased the precision for 2 digits and was able to obtain the following result:
and the typical actuator outputs log as follow:
> Precision of tol for float has been changed

- matrix/Matrix.hpp
- matrix/SquareMatrix.hpp
- matrix/helper_functions.hpp
In order for some builds to work where the Type is double, we need to manually coerce the type so that we don't get compiler warnings of implicit float -> double conversions
> Coerce default epsilon values to Type

- matrix/SquareMatrix.hpp
- test/matrixAssignment.cpp
Fix some compiler warnings and inconsistencies in the algorithm. Also ignore a line in the coverage which shouldn't happen anyways.
> Type coercion cleanup

- matrix/Dcm.hpp
- matrix/Matrix.hpp
This actually optimizes a bit better because the function call can be avoided entirely.
Saves about 7.3 kB of flash on px4_fmu-v5_default.
> Matrix: use naive per element copy instead of memcpy call
