matrix/math.hpp
These changes are required for hexagon support.
=> Added hexagon support

matrix/math.hpp
Signed-off-by: Mark Charlebois <charlebm@gmail.com>
=> Added dspal_math.h for missing constants

.travis.yml, CMakeLists.txt, doc/.gitignore, doc/euler_gimbal_lock.ipynb, matrix/Euler.hpp, test/CMakeLists.txt, test/attitude.cpp
I didn't really look much into it but using the old calculation QGC only displays yaw from west over north to east. So it seems like yaw is in the range [-pi/2, pi/2].
=> fix euler calculation

matrix/Dcm.hpp, matrix/Matrix.hpp, matrix/SquareMatrix.hpp, matrix/Vector3.hpp, test/CMakeLists.txt, test/attitude.cpp, test/hatvee.cpp, test/squareMatrix.cpp
all nice separated by descriptive commits
thanks in advance
=> Features and fixes

matrix/Euler.hpp, matrix/Matrix.hpp
Euler.hpp didn't recognize M_PI, need to add a #Define. Matrix.hpp didn't recognize and, need to change it to &&.
=> Define M_PI float, change logical and to &&

CMakeLists.txt, matrix/AxisAngle.hpp, matrix/Dcm.hpp, matrix/Quaternion.hpp, matrix/math.hpp, test/attitude.cpp, test/matrixAssignment.cpp
This closes https://github.com/PX4/Matrix/issues/18
@tumbili @bkueng @LorenzMeier 
to_axis_angle, from_axis_angle should now be deprecated.
=> Axis angle

matrix/Dcm.hpp, test/attitude.cpp
This fixes the coverage and formatting issues in #31.
=> add renormalize method

matrix/helper_functions.hpp
Tested via https://github.com/PX4/Firmware/pull/6524
=> Qurt isfinite

matrix/Quaternion.hpp
^(-1) went missing and some phrase was inprecise
=> Quaternion: Correcting Comments

matrix/Dcm.hpp, matrix/Quaternion.hpp, test/attitude.cpp
While implementing https://github.com/PX4/Firmware/pull/8003 I came across some possible extensions to optimize performance. I made changes to not waste too much cycles for computing the same or afterwards unused values.
Currently there's nothing I want to further add to this pr.
=> Quat to Dcm Extensions

CMakeLists.txt, README.md, scripts/format.sh, test/CMakeLists.txt
I think it would be good to be consistent about using spaces instead of indent in the code and cmake files.
=> Fix README/cmake format.

matrix/LeastSquaresSolver.hpp, matrix/math.hpp, test/CMakeLists.txt, test/least_squares.cpp, test/test_data.py
For a control algorithm I'm working on, I am going to need this least squares solver. It does a QR decomposition using the householder algorithm.
User needs to make sure that:
* Rank(A) = N
* M >= N
=> Least squares solver for MxN matrices using QR householder algorithm

test/matrixMult.cpp
We had no tests to see if it worked with non-square matrices, that output shape is correct, etc.
=> Test non-square matrix multiplication

matrix/Matrix.hpp
This fixes a missing type promotion.
=> Fix type for division.

matrix/AxisAngle.hpp, matrix/Euler.hpp, matrix/Matrix.hpp, matrix/Quaternion.hpp
Follow up of small things that catched my eye after looking through https://github.com/PX4/Matrix/pull/95
=> Fix some template type conversions and style

test/CMakeLists.txt
This enables branch coverage in the coverage report
=> Enable branch coverage

matrix/Dual.hpp, matrix/Matrix.hpp, matrix/Quaternion.hpp, matrix/Vector.hpp, matrix/math.hpp, test/CMakeLists.txt, test/dual.cpp
This adds the ability to do autodifferentiation. This is a high-perfomance method of calculating derivatives, partial derivatives and jacobians without depending on code generation or numerical differences. It gives accuracy and speed similar to generated code, but allows things not usually allowed in code generators like `if` blocks, `for` loops, discontinuities such as `min`/`max`/`fmod`, as well as the usual `sin`/`cos`/`asin`/`tan`/`atan`/`sqrt` etc.
Simple usage is in the tests, and here:
Eg given a function  **f(x,y,z) = x^2 + 2xy + 3y^2 + z** which we want the partial derivatives _d/dx_ and _d/dy_ at the point **(0.5, -0.8, 2)**
We just define the function as if we are evaluating the regular result, templated on the type in the vector.
```C++
template <typename T>
T …
```
=> Automatic Differentiation 'Dual' Type

matrix/Matrix.hpp, test/matrixAssignment.cpp
This PR adds the functionality to compute a constrained Matrix with a scalar or another Matrix of the same size. It provides the functionality of min, max and constrain.
@jkflying
=> Add min, max, constrain function for Matrix

README.md, matrix/Slice.hpp, test/slice.cpp
This is useful for setting a part of an matrix to a certain value, e.g. zero
=> Slice assign value

matrix/Matrix.hpp, matrix/Slice.hpp, matrix/SquareMatrix.hpp, test/matrixAssignment.cpp
Add function to set a row or a column also to a single value. E.g. 0
And some small fixes
=> Set Matrix's col and row to single value

matrix/SquareMatrix.hpp, test/squareMatrix.cpp
Such as:	
* setOffDiagZero
* makeDiag
* makeBlockSymmetric
* makeRowColSymmetric
* isBlockSymmetric
* isRowColSymmetric
=> Add several functions that are useful for coavriance matrices

matrix/Quaternion.hpp, matrix/helper_functions.hpp, test/attitude.cpp, test/copyto.cpp
@MaEtUgR Thanks for showing me these corner cases.
=> Catch quaternion canonical corner cases

matrix/SquareMatrix.hpp
This saves an addition for each element in the matrix.
=> Use faster but less accurate average

matrix/Matrix.hpp, test/matrixAssignment.cpp
- First commit: Follow up to https://github.com/PX4/Matrix/pull/105/files#r348386226
- Second commit: some comment, style refactoring
=> Small min max refactor

matrix/Slice.hpp, test/slice.cpp
Not sure if we want the addition and subtraction of a scalar.
=> Add more assignment operators for slices

matrix/Quaternion.hpp
=> fix conjugate_inversed comment

matrix/Slice.hpp
Missed the const modifier last time. Can we get this in quickly?
=> Add missing const modifier

matrix/Matrix.hpp, test/matrixMult.cpp
Lower stack usage for += and -= matrix operations, as well as *= and /= scalar-matrix operations
=> Do += -= and scalar *= /= in place

matrix/SparseVector.hpp
Comparisons of integer with different signedness cause issues during integration into ECL. Size_t is he common integer used in Matrix library. This PR changes to size_t everywhere, where it is possible.
=> use size_t instead of int in sparseVector

matrix/SparseVector.hpp
urgently need to get Matrix/master into Firmware https://github.com/PX4/Firmware/pull/15520
=> comply with Firmware style requirements

matrix/SparseVector.hpp, test/sparseVector.cpp
Adds a method to compute x.T * A * x, where x is a SparseVector of size M and A is a square matrix of size MxM.
=> Sparse quadratic form

matrix/Vector3.hpp, test/vector3.cpp
Self-explanatory.  Adds ability to add/subtract a scalar value from all elements of a Vector3.
=> Vector3: Add operator+/- for scalars

matrix/AxisAngle.hpp, matrix/Dcm.hpp, matrix/Euler.hpp, matrix/Quaternion.hpp, matrix/Scalar.hpp, matrix/SquareMatrix.hpp, matrix/Vector.hpp, matrix/Vector2.hpp, matrix/Vector3.hpp
=> add double precision alias declarations and remove typedefs

matrix/Euler.hpp
@MaEtUgR how about this instead?
=> Euler: simplify DCM constructor

matrix/Euler.hpp
Saves quite a bit of flash with optimization enabled.
=> Euler: improve quaternion constructor
